web:
  build: .
  volumes:
        - ./src:/usr/src/app/src
  ports:
    - '8080:8080'
  environment:
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=docker
  links:
    - postgres

postgres:
    image: postgres
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
